In [8]:
import numpy as np

In [9]:
# 1D Array 
el = np.array([1, 2, 3]) 
el 

# el = [1, 2, 3]

array([1, 2, 3])

In [10]:
# 2D Array - matrix 
psy = np.array([(2.4, -1.5, 1.2), (2.3, -2.4, -5.6)])
psy

# psy = [2.4 -1.5  1.2
#        2.3 -2.4 -5.6]

array([[ 2.4, -1.5,  1.2],
       [ 2.3, -2.4, -5.6]])

In [12]:
# 3D Array - tensor 
kongroo = np.array([[(1.1,2,3.4),(7,2.5,9)],[(1,2,3),(9,8,7)]])
kongroo

array([[[1.1, 2. , 3.4],
        [7. , 2.5, 9. ]],

       [[1. , 2. , 3. ],
        [9. , 8. , 7. ]]])

In [22]:
# Create an array of m x n x p zeros 
x = np.zeros((2, 3))  # 2 rows, 3 columns 
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
y = np.ones((2, 3)) 
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Syntax: np.linspace(first:last:number of samples) 
np.linspace(3,7,10)


array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

In [19]:
# Syntax: np.arange(first:last-interval:interval)

z = np.arange(3, 7, 0.5)
z

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [18]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [17]:
# identity matrix: np.eye(m)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#Viewing the contents on a numpy file
#Syntax = np.load('filename.npy')
data = np.load('epk.npy')
data

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [16]:
np.random.random((2,3))

array([[0.49452549, 0.62710722, 0.88736143],
       [0.78480672, 0.2156418 , 0.97194807]])

In [14]:
data.shape

(2, 2, 3)

In [ ]:
data.ndim

In [15]:
data.size

12

In [24]:
a = np.array([(2,4,6),(8,10,12)])
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
b = np.array([(4,9),(16,25),(36,49)])
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [26]:
c = np.array([2,3,5])
c

array([2, 3, 5])

In [27]:
# Element-wise
c-a

array([[ 0, -1, -1],
       [-6, -7, -7]])

In [28]:
a+c

array([[ 4,  7, 11],
       [10, 13, 17]])

In [29]:
a*c

array([[ 4, 12, 30],
       [16, 30, 60]])

In [30]:
c*a

array([[ 4, 12, 30],
       [16, 30, 60]])

In [31]:
a/c

array([[1.        , 1.33333333, 1.2       ],
       [4.        , 3.33333333, 2.4       ]])

In [32]:
c/a

array([[1.        , 0.75      , 0.83333333],
       [0.25      , 0.3       , 0.41666667]])

In [33]:
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [34]:
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [35]:
np.exp(b)

array([[5.45981500e+01, 8.10308393e+03],
       [8.88611052e+06, 7.20048993e+10],
       [4.31123155e+15, 1.90734657e+21]])

In [36]:
np.sqrt(b)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [37]:
np.sin(b)

array([[-0.7568025 ,  0.41211849],
       [-0.28790332, -0.13235175],
       [-0.99177885, -0.95375265]])

In [38]:
np.log(b)

array([[1.38629436, 2.19722458],
       [2.77258872, 3.21887582],
       [3.58351894, 3.8918203 ]])

In [39]:
a = np.array([2,3,5])
a

array([2, 3, 5])

In [40]:
b = np.array([(1,2,5),(4,5,6),(7,8,9)])
b

array([[1, 2, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# = is an assignment operator
c = a
c

array([2, 3, 5])

In [42]:
a == b

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [43]:
b < 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [44]:
a > 2

array([False,  True,  True])

In [45]:
# As a group 
np.array_equal(a,b) 

False

In [46]:
np.array_equal(a,c)

True

In [ ]:
# Subsetting, slicing, and indexing of arrays

In [47]:
A = np.array([(1,2,3),(4,5,6),(7,8,9)]) 
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# Subsetting - getting a certain element from the array or structure 
A[1,1] #or A[1,1]

5

In [49]:
A[2,1]

8

In [50]:
# Slicing - getting the portion from an array or structure
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
A[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
A[0:3,2]

array([3, 6, 9])

In [55]:
A[1]

array([4, 5, 6])

In [59]:
# Indexing - getting a certain element or depending on the conditions 
A[A<7] 

array([1, 2, 3, 4, 5, 6])

In [60]:
A[A>2]

array([3, 4, 5, 6, 7, 8, 9])

In [61]:
A[A==5]

array([5])

In [62]:
# ndarray Manipulation 
a = np.array([3,2,1])
a

array([3, 2, 1])

In [63]:
b = np.array([(4,6,5),(3,2,1)])
b

array([[4, 6, 5],
       [3, 2, 1]])

In [64]:
c = np.linspace(10,20,3)
c

array([10., 15., 20.])

In [65]:
d = np.full((2,2),7)
d

array([[7, 7],
       [7, 7]])

In [66]:
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [67]:
a.sort()
a

array([1, 2, 3])

In [68]:
b

array([[4, 6, 5],
       [3, 2, 1]])

In [69]:
b.sort(axis=0) #pag axis 0 by row
b

array([[3, 2, 1],
       [4, 6, 5]])

In [70]:
b.sort(axis=1) #pag axis 1 by column
b

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.shape(b)

(2, 3)

In [102]:
b.reshape(6,1).shape
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [93]:
b.resize(6,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [94]:
d

array([[7, 7],
       [7, 7]])

In [95]:
e

array([[1., 0.],
       [0., 1.]])

In [96]:
np.append(d,e)

array([7., 7., 7., 7., 1., 0., 0., 1.])

In [97]:
a

array([1, 2, 3])

In [98]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [99]:
np.delete(a,[2])

array([1, 2])

In [100]:
np.concatenate((a,c),axis=0)

array([ 1.,  2.,  3., 10., 15., 20.])

In [103]:
np.vstack((a,c))

array([[ 1.,  2.,  3.],
       [10., 15., 20.]])

In [104]:
np.hstack((d,e))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [105]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [106]:
np.vsplit(e,2)

[array([[1., 0.]]), array([[0., 1.]])]